version: "3.8"

services:
  app-build:
    container_name: app-build
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.2"
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
